/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CHabitacion;
import Controlador.CPasajero;
import Modelo.Reserva;
import java.sql.Date;


import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class Habitacion extends javax.swing.JFrame {

    /**
     * Creates new form Habitacion
     */
    public Habitacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("CONFIRMACION RESERVA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, 30));

        jLabel2.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HABITACIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_cerrar1.png"))); // NOI18N
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_cerrar3.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_cerrar2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 30, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_back1.jpg"))); // NOI18N
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_back3.jpg"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_back2.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 30, 40));

        jButton3.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jButton3.setText("LIMPIAR ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 100, 30));

        jDateChooser1.setDateFormatString("dd-MMM-yyyy HH:mm:ss");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 170, -1));
        Calendar  fechactual;
        fechactual= new GregorianCalendar();
        jDateChooser1.setCalendar(fechactual);

        jDateChooser2.setDateFormatString("dd-MMM-yyyy HH:mm:ss");
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 170, -1));

        jLabel7.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MODALIDAD / TIEMPO:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HORA CHECK IN :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID PASAJERO TITULAR:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "idReserva", "Habitacion", "Modalidad", "FechaIngreso", "FechaEgreso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 480, 50));

        jButton7.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        jButton7.setText("MOSTRAR  HABITACIONES");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 190, 30));

        jButton8.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jButton8.setText("RESERVAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 140, 30));

        jLabel13.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NOMBRE HABITACIÓN:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 30));

        jLabel8.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("HABITACIONES DISPONIBLES");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "PrecioMomento", "PrecioJornada", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 480, 100));

        jComboBox1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Amorlila", "Gradocinco", "Oasisdeplacer", "Pololeozarpao", "Todopasando" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 30));

        jComboBox2.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Momento", "Jornada" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 140, 30));

        jLabel11.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HORA CHECK OUT :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jTextField1.setDisabledTextColor(new java.awt.Color(255, 51, 1));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 80, 20));

        jTextField2.setDisabledTextColor(new java.awt.Color(255, 51, 1));
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 80, 20));

        jLabel14.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("CONFIRME EN EL CAMPO DE TEXTO EL ID DE PASAJERO TITULAR ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/habitacion-fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 720, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    this.dispose();
    new Pasajero().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //jComboBox1.setSelectedItem(null);
       // jComboBox2.setSelectedItem(null);
        //jComboBox3.setSelectedItem(null);
       
        jDateChooser2.setDate(null);
        jComboBox1.setSelectedItem(null);
       jComboBox2.setSelectedItem(null);
       jTextField1.setText("");
        //jTextField2.setText("");
             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
JOptionPane.showMessageDialog(rootPane, "Las siguientes habitaciones están disponibles"); 
    
        DefaultTableModel modelo;  
        modelo = (DefaultTableModel) jTable2.getModel(); 
        jTable2.setModel(modelo); 
        modelo.setRowCount(0); // le asignamos que comienze desde la fila 0
       
       Controlador.CHabitacion h = new Controlador.CHabitacion(); // se crea un objeto de la clase controlador donde esta el método para mostrar
         // Se recibe el Rut por parametro (para buscarlo) en el campo de texto JTextField6
       List<Modelo.Habitacion> list= h.mostrarHabitaciones(); // Se crea una lista asociada al nombre de la clase del Reporte, luego el objeto de la clasecontrolador se le aplica el método para mostrar y se le pasa por parametro la variable Rut
      
       
       Object rowData[] = new Object[4]; // se crea un arreglo de Objetos rowData para leer las filas que traen las columnas, en este caso son 9 campos
       
       
       
       for (int i = 0; i < list.size(); i++) {   // con un for se lee el arreglo
           
           rowData[0] = list.get(i).getNombreHab();    //cada posición de la columna se trae con el método get de cada atributo creados en la clase modelo     
           rowData[1] = list.get(i).getPrecio_Momento();
           rowData[2] = list.get(i).getPrecio_Jornada();
           rowData[3] = list.get(i).getDisponibilidad();
         
          modelo.addRow(rowData);   // con esta instrucción se traspasan los elementos de la lista a la tabla modelo
         
          }         // TODO add your handling code here:
        
          CHabitacion cp = new CHabitacion();

        
try {
        List<Reserva> lista = cp.mostraridPasTitular();

        Object campo[] = new Object[1];

        campo[0] = lista.get(0).getIdPasajeroTitular();
    

        jTextField2.setText((String.valueOf(campo[0]) )); 
      //  jTextField1.setText((String) campo[0]);
       
}

catch (Exception ex) {
           JOptionPane.showMessageDialog(this, "lleno los campos y pulse reservar");
}
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
 if ( jComboBox1.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un nombre de habitación ");
            jComboBox1.requestFocus();
            return;
        }
   if ( jComboBox2.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar una modalidad ");
            jComboBox2.requestFocus();
            return;
        }
 
 
     
          if (jDateChooser2.getDate()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una fecha  y hora de egreso validas");
            jDateChooser2.requestFocus();
            return;
        }
          
           /*if ( jTextField1.getSelectedText()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debes comfirmar el ID del Pasajero titular ");
            jTextField1.requestFocus();
            return; 
        }*/
      
        Modelo.Reserva dts = new Modelo.Reserva();
        CHabitacion func = new CHabitacion();

        int seleccionado = jComboBox1.getSelectedIndex();
        dts.setHabitaciones_NombreHab((String) jComboBox1.getItemAt(seleccionado));
        String habi=jComboBox1.toString();
        int seleccionado2 = jComboBox2.getSelectedIndex();
        dts.setModalidad((String) jComboBox2.getItemAt(seleccionado2));
        
        
        Calendar cal;
        int d,m,a,ho,mi,s;
        cal=jDateChooser1.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR) - 1900;
        ho=cal.get(Calendar.HOUR);
        mi=cal.get(Calendar.MINUTE);
        s=cal.get(Calendar.SECOND);
        dts.setFecha_Ingreso(new Date(a,m,d));
        
        
        cal=jDateChooser1.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR) - 1900;
        dts.setFecha_Egreso(new Date(a,m,d));
        
        dts.setPasajeroTitular_IdPasajeroTitular(Integer.parseInt(jTextField1.getText()) );  
   
        func.Reservar(dts) ;
        JOptionPane.showMessageDialog(rootPane, "la reserva fue ingresada satisfactoriamente"); 
       
        DefaultTableModel modelo;  // Se llama la clase DefaultTableModel.. y se intancia un objeto modelo
       modelo = (DefaultTableModel) jTable1.getModel(); // el objeto modelo se iguala al nombre de la tabla que se va a mostrar (jTable1)
       jTable1.setModel(modelo); // se le envía el modelo para que lo muestre
       modelo.setRowCount(0); // le asignamos que comienze desde la fila 0
       
       Controlador.CHabitacion h = new Controlador.CHabitacion(); // se crea un objeto de la clase controlador donde esta el método para mostrar
         // Se recibe el Rut por parametro (para buscarlo) en el campo de texto JTextField6
       List<Modelo.Reserva> list= h.mostrarReserva(); // Se crea una lista asociada al nombre de la clase del Reporte, luego el objeto de la clasecontrolador se le aplica el método para mostrar y se le pasa por parametro la variable Rut
      
       
       Object rowData[] = new Object[5]; // se crea un arreglo de Objetos rowData para leer las filas que traen las columnas, en este caso son 9 campos
       
       
       
       for (int i = 0; i < list.size(); i++) {   // con un for se lee el arreglo
           
           rowData[0] = list.get(i).getIdReservaHabitacion();      //cada posición de la columna se trae con el método get de cada atributo creados en la clase modelo     
           rowData[1] = list.get(i).getModalidad();
           rowData[2] = list.get(i).getFecha_Ingreso();
           rowData[3] = list.get(i).getFecha_Egreso();
           rowData[4] = list.get(i).getHabitaciones_NombreHab();
           
           modelo.addRow(rowData);   // con esta instrucción se traspasan los elementos de la lista a la tabla modelo
         
          } 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Habitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
