/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CPasajero;
import Controlador.Ctrabajador;
import Modelo.Reporte;
import java.sql.Date;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class Pasajero extends javax.swing.JFrame {

    /**
     * Creates new form Pasajero
     */
    public Pasajero() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void habilitar() {
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jComboBox1.setEnabled(true);
        jTextField6.setEnabled(true);
        jDateChooser1.setEnabled(true);

    }
    
    public void inhabilitar() {
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jComboBox1.setEnabled(false);
        jTextField6.setEnabled(false);
        jDateChooser1.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField7 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lato", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASAJERO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jButton4.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jButton4.setText("SELECCIONAR HABITACIÓN");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, 240, 30));

        jLabel4.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("APELLIDO PATERNO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDO MATERNO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GÉNERO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NACIONALIDAD:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RUT:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_back1.jpg"))); // NOI18N
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_back3.jpg"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_back2.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 30, 40));

        jLabel11.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("PASAJEROS ACOMPAÑANTES");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jTextField1.setDisabledTextColor(new java.awt.Color(255, 51, 1));
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 260, -1));

        jTextField2.setDisabledTextColor(new java.awt.Color(255, 51, 0));
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 250, -1));

        jTextField3.setDisabledTextColor(new java.awt.Color(255, 51, 1));
        jTextField3.setDoubleBuffered(true);
        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 250, -1));

        jComboBox1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, -1));

        jTextField6.setDisabledTextColor(new java.awt.Color(255, 51, 1));
        jTextField6.setDoubleBuffered(true);
        jTextField6.setEnabled(false);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 290, -1));

        jDateChooser1.setEnabled(false);
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 130, -1));

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 190, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Titular", "Acompañante" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 120, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_cerrar1.png"))); // NOI18N
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_cerrar3.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_cerrar2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 40));

        jButton5.setFont(new java.awt.Font("Lato", 1, 11)); // NOI18N
        jButton5.setText("INGRESAR TITULAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        jButton6.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jButton6.setText("VERIFICAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jButton7.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        jButton7.setText("LIMPIAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 100, -1));

        jLabel12.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TIPO DE PASAJERO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("REVISE EL RUT DEL PASAJERO SIN PUNTOS, GUIONES Y SIN CARACTER VERIFICADOR");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jButton8.setFont(new java.awt.Font("Lato", 1, 11)); // NOI18N
        jButton8.setText("INGRESAR ACOMPAÑANTE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "APaterno", "AMaterno", "Nacionalidad", "Sexo"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, 60));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "APaterno", "AMaterno", "Nacionalidad", "Sexo"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, 50));

        jLabel13.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("TODOS LOS CAMPOS SON OBLIGATORIOS");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("PASAJERO TITULAR");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pasajeros-fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -110, 720, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
        new Menu().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        this.dispose();
        new Habitacion().setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedItem(null);
        jTextField6.setText("");
        jTextField7.setText("");
        jDateChooser1.setDate(null);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        CPasajero cp = new CPasajero();

        int Rut = Integer.parseInt(jTextField7.getText());
try {
        List<Modelo.Pasajero> list = cp.verificarPasajero(Rut);

        Object campo[] = new Object[6];

        campo[0] = list.get(0).getNombre();
        campo[1] = list.get(0).getAPaterno();
        campo[2] = list.get(0).getAMaterno();
        campo[3] = list.get(0).getNacionalidad();
        campo[4] = list.get(0).getSexo();
        campo[5] = list.get(0).getFecha_Nacimiento();

        //jTextField1.setText((String.valueOf(campo[1]) )); 
        jTextField1.setText((String) campo[0]);
        jTextField2.setText((String) campo[1]);
        jTextField3.setText((String) campo[2]);
        jTextField6.setText((String) campo[3]);
        jComboBox1.setSelectedItem(((String) campo[4]));        //  setName((String) campo[3]);  
        jDateChooser1.setDate((Date) campo[5]);
}

catch (Exception ex) {
           JOptionPane.showMessageDialog(this, "Pulse Ingresar Pasajero Titular o Acomapañante para habilitar los campos de texto");
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.habilitar();
        if (jTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Nombre para el cliente");
            jTextField1.requestFocus();
            return;
        }
        if (jTextField2.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un apellido paterno para el cliente");
            jTextField2.requestFocus();
            return;
        }
        
        if (jTextField3.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un apellido materno para el cliente");
            jTextField3.requestFocus();
            return;
        }
        
        if (jTextField6.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar Nacionalidad");
            jTextField6.requestFocus();
            return;
        }

       if (jDateChooser1.getDate()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una fecha de nacimiento valida");
            jDateChooser1.requestFocus();
            return;
        }
        
        if ( jComboBox1.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un sexo valido");
            jComboBox1.requestFocus();
            return;
        }

       
        
        
        Modelo.Pasajero dts = new Modelo.Pasajero();
        Modelo.PasajeroTitular cls= new Modelo.PasajeroTitular();
        CPasajero func = new CPasajero();

        dts.setNombre(jTextField1.getText());
        dts.setRut(Integer.parseInt(jTextField7.getText()) );  
        dts.setAPaterno(jTextField2.getText());
        dts.setAMaterno(jTextField3.getText());
        dts.setNacionalidad(jTextField6.getText());
        
        Calendar cal;
        int d,m,a;
        cal=jDateChooser1.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR) - 1900;
        dts.setFecha_Nacimiento(new Date(a,m,d));
        
     
        int seleccionado = jComboBox1.getSelectedIndex();
        dts.setSexo((String) jComboBox1.getItemAt(seleccionado));
        int seleccionado2 = jComboBox3.getSelectedIndex();
       // cls.setTipo_Cliente((String) jComboBox3.getItemAt(seleccionado2));
       
         JOptionPane.showMessageDialog(rootPane, "Solamente El Cliente Titular puede escoger habitación");
         jButton4.setEnabled(true);
         func.ingresarPasajeroTitular(dts);
        JOptionPane.showMessageDialog(rootPane, "el cliente fue registrado satisfactoriamente"); 
        jButton5.setEnabled(false);
        DefaultTableModel modelo;  // Se llama la clase DefaultTableModel.. y se intancia un objeto modelo
       modelo = (DefaultTableModel) jTable2.getModel(); // el objeto modelo se iguala al nombre de la tabla que se va a mostrar (jTable1)
       jTable2.setModel(modelo); // se le envía el modelo para que lo muestre
       modelo.setRowCount(0); // le asignamos que comienze desde la fila 0
       
       Controlador.CPasajero p = new Controlador.CPasajero(); // se crea un objeto de la clase controlador donde esta el método para mostrar
         // Se recibe el Rut por parametro (para buscarlo) en el campo de texto JTextField6
       List<Modelo.Pasajero> list= p.mostrarPasajeroTitular(); // Se crea una lista asociada al nombre de la clase del Reporte, luego el objeto de la clasecontrolador se le aplica el método para mostrar y se le pasa por parametro la variable Rut
      
       
       Object rowData[] = new Object[6]; // se crea un arreglo de Objetos rowData para leer las filas que traen las columnas, en este caso son 9 campos
       
       
       
       for (int i = 0; i < list.size(); i++) {   // con un for se lee el arreglo
           
           rowData[0] = list.get(i).getRut();    //cada posición de la columna se trae con el método get de cada atributo creados en la clase modelo     
           rowData[1] = list.get(i).getNombre();
           rowData[2] = list.get(i).getAPaterno();
           rowData[3] = list.get(i).getAMaterno();
           rowData[4] = list.get(i).getNacionalidad();
           rowData[5] = list.get(i).getSexo();
           modelo.addRow(rowData);   // con esta instrucción se traspasan los elementos de la lista a la tabla modelo
         
          } 
                
              
        
        
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 this.habilitar();
        if (jTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Nombre para el cliente");
            jTextField1.requestFocus();
            return;
        }
        if (jTextField2.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un apellido paterno para el cliente");
            jTextField2.requestFocus();
            return;
        }
        
        if (jTextField3.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un apellido materno para el cliente");
            jTextField3.requestFocus();
            return;
        }
        
        if (jTextField6.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar Nacionalidad");
            jTextField6.requestFocus();
            return;
        }

       if (jDateChooser1.getDate()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una fecha de nacimiento valida");
            jDateChooser1.requestFocus();
            return;
        }
        
        if ( jComboBox1.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un sexo valido");
            jComboBox1.requestFocus();
            return;
        }

       
        
        
        Modelo.Pasajero dts = new Modelo.Pasajero();
        
        CPasajero func = new CPasajero();

        dts.setNombre(jTextField1.getText());
        dts.setRut(Integer.parseInt(jTextField7.getText()) );  
        dts.setAPaterno(jTextField2.getText());
        dts.setAMaterno(jTextField3.getText());
        dts.setNacionalidad(jTextField6.getText());
        
        Calendar cal;
        int d,m,a;
        cal=jDateChooser1.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR) - 1900;
        dts.setFecha_Nacimiento(new Date(a,m,d));
        
     
        int seleccionado = jComboBox1.getSelectedIndex();
        dts.setSexo((String) jComboBox1.getItemAt(seleccionado));
        int seleccionado2 = jComboBox3.getSelectedIndex();
       // cls.setTipo_Cliente((String) jComboBox3.getItemAt(seleccionado2));
       
         JOptionPane.showMessageDialog(rootPane, "Solamente El Cliente Titular puede escoger habitación");
         jButton4.setEnabled(true);
         func.ingresarPasajeroAcompañante(dts);
        JOptionPane.showMessageDialog(rootPane, "el cliente fue registrado satisfactoriamente"); 
       /*int msj= JOptionPane.showInternalConfirmDialog(rootPane, "¿Desea agregar otro pasajero acompañante?");
       if (msj == JOptionPane.YES_OPTION) {
                            
                        }
                        if (msj == JOptionPane.NO_OPTION) {
                            jButton8.setEnabled(false);}
                        
                            if (msj == JOptionPane.CANCEL_OPTION) {
                            
                        }*/
         DefaultTableModel modelo;  // Se llama la clase DefaultTableModel.. y se intancia un objeto modelo
       modelo = (DefaultTableModel) jTable3.getModel(); // el objeto modelo se iguala al nombre de la tabla que se va a mostrar (jTable1)
       jTable3.setModel(modelo); // se le envía el modelo para que lo muestre
       modelo.setRowCount(0); // le asignamos que comienze desde la fila 0
       
       Controlador.CPasajero p = new Controlador.CPasajero(); // se crea un objeto de la clase controlador donde esta el método para mostrar
         // Se recibe el Rut por parametro (para buscarlo) en el campo de texto JTextField6
       List<Modelo.Pasajero> list= p.mostrarPasajeroAcompañante(); // Se crea una lista asociada al nombre de la clase del Reporte, luego el objeto de la clasecontrolador se le aplica el método para mostrar y se le pasa por parametro la variable Rut
      
       
       Object rowData[] = new Object[6]; // se crea un arreglo de Objetos rowData para leer las filas que traen las columnas, en este caso son 9 campos
       
       
       
       for (int i = 0; i < list.size(); i++) {   // con un for se lee el arreglo
           
           rowData[0] = list.get(i).getRut();    //cada posición de la columna se trae con el método get de cada atributo creados en la clase modelo     
           rowData[1] = list.get(i).getNombre();
           rowData[2] = list.get(i).getAPaterno();
           rowData[3] = list.get(i).getAMaterno();
           rowData[4] = list.get(i).getNacionalidad();
           rowData[5] = list.get(i).getSexo();
           modelo.addRow(rowData);   // con esta instrucción se traspasan los elementos de la lista a la tabla modelo
         
          }                      
                
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pasajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
